from gestor_archivos.resumir_texto import dividir_texto_en_palabras_correctas, generar_archivo_de_palabras, mezclar_archivos, crear_archivo_de_palabras
from juego_ahorcado.ahorcado import jugar

tabla_de_longitud = crear_archivo_de_palabras()

jugar(tabla_de_longitud)